/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;
import dominio.Evaluacion;
import dominio.Persona;
import dominio.Restaurante;
import dominio.Sorteo;

/**
 *
 * @author bruno
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    private Restaurante restaurante;
    private int cantidadEstrellas;

    public VentanaInicio(Restaurante r) {
        initComponents();
        restaurante = r;
        this.esconder();
        inicio.setVisible(true);
        this.setSize(805, 630);
        this.setResizable(false);
        cantidadEstrellas = 0;
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {

                restaurante.guardar();

                int i = JOptionPane.showConfirmDialog(null, "Desea finalizar el programa?", null, YES_NO_OPTION);
                if (i == 0) {
                    System.exit(0);//cierra aplicacion
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ingresarEvaluacion = new javax.swing.JPanel();
        btnAtrasEvaluacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReseniaPersona = new javax.swing.JTextArea();
        btnEnviarEvaluacion = new javax.swing.JButton();
        txtNombrePersona = new javax.swing.JTextField();
        txtTelPersona = new javax.swing.JTextField();
        txtMailPersona = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCiPersona = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        s1 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        s5 = new javax.swing.JButton();
        opcionesEmpleado = new javax.swing.JPanel();
        btnAtrasOpEmpleado = new javax.swing.JButton();
        btnEditarRestaurante = new javax.swing.JButton();
        btnSortear = new javax.swing.JButton();
        btnVerEvaluaciones = new javax.swing.JButton();
        btnVerSorteos = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        editarRestaurante = new javax.swing.JPanel();
        btnAtrasRestaurante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreRest = new javax.swing.JTextField();
        txtDireccionRest = new javax.swing.JTextField();
        txtHorarioRest = new javax.swing.JTextField();
        txtTipoComidaRest = new javax.swing.JTextField();
        btnGuardarRestaurante = new javax.swing.JButton();
        sortear = new javax.swing.JPanel();
        btnAtrasRealizarSorteo = new javax.swing.JButton();
        btnRealizarSorteo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantGanadoresSorteo = new javax.swing.JTextField();
        txtPremioSorteo = new javax.swing.JTextField();
        lblGanadores = new javax.swing.JLabel();
        evaluaciones = new javax.swing.JPanel();
        btnAtrasVerEvaluaciones = new javax.swing.JButton();
        panelEvaluaciones = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVer1Evaluacion = new javax.swing.JButton();
        btnEliminarEvaluacion = new javax.swing.JButton();
        verEvaluacion = new javax.swing.JPanel();
        btnAtrasVerEvaluacion = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        e1 = new javax.swing.JButton();
        e2 = new javax.swing.JButton();
        e3 = new javax.swing.JButton();
        e4 = new javax.swing.JButton();
        e5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        sorteos = new javax.swing.JPanel();
        btnVolverVerSorteos = new javax.swing.JButton();
        panelSorteos = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnVer1Sorteo = new javax.swing.JButton();
        btnEliminarSorteo = new javax.swing.JButton();
        verSorteo = new javax.swing.JPanel();
        btnAtrasVerSorteo = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        inicio.setLayout(null);

        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        inicio.add(btnCliente);
        btnCliente.setBounds(410, 300, 120, 60);

        btnEmpleado.setText("Empleado");
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });
        inicio.add(btnEmpleado);
        btnEmpleado.setBounds(230, 300, 120, 60);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1.jpg"))); // NOI18N
        inicio.add(jLabel16);
        jLabel16.setBounds(0, 0, 800, 600);

        getContentPane().add(inicio);

        ingresarEvaluacion.setBackground(new java.awt.Color(219, 182, 173));

        btnAtrasEvaluacion.setText("volver");
        btnAtrasEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasEvaluacionActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre:");

        jLabel8.setText("Telefono:");

        jLabel9.setText("Correo:");

        jLabel10.setText("Estrellas:");

        jLabel11.setText("Reseña:");

        txtReseniaPersona.setColumns(20);
        txtReseniaPersona.setRows(5);
        jScrollPane1.setViewportView(txtReseniaPersona);

        btnEnviarEvaluacion.setText("Enviar evaluacion");
        btnEnviarEvaluacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEnviarEvaluacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnEnviarEvaluacionFocusLost(evt);
            }
        });
        btnEnviarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEvaluacionActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("* El correo ingresado no es correcto");

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("* El telefono ingresado no es correcto");

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("* La CI ingresada no es correcta");

        jLabel15.setText("CI:");

        s1.setBackground(new java.awt.Color(219, 182, 173));
        s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        s1.setBorderPainted(false);
        s1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s1FocusLost(evt);
            }
        });
        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s1MouseExited(evt);
            }
        });
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        s2.setBackground(new java.awt.Color(219, 182, 173));
        s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        s2.setBorderPainted(false);
        s2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s2FocusLost(evt);
            }
        });
        s2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s2MouseExited(evt);
            }
        });
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        s3.setBackground(new java.awt.Color(219, 182, 173));
        s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        s3.setBorderPainted(false);
        s3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s3FocusLost(evt);
            }
        });
        s3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s3MouseExited(evt);
            }
        });
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        s4.setBackground(new java.awt.Color(219, 182, 173));
        s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        s4.setBorderPainted(false);
        s4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s4FocusLost(evt);
            }
        });
        s4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s4MouseExited(evt);
            }
        });
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        s5.setBackground(new java.awt.Color(219, 182, 173));
        s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        s5.setBorderPainted(false);
        s5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s5FocusLost(evt);
            }
        });
        s5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s5MouseExited(evt);
            }
        });
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ingresarEvaluacionLayout = new javax.swing.GroupLayout(ingresarEvaluacion);
        ingresarEvaluacion.setLayout(ingresarEvaluacionLayout);
        ingresarEvaluacionLayout.setHorizontalGroup(
            ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarEvaluacionLayout.createSequentialGroup()
                .addComponent(btnAtrasEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ingresarEvaluacionLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(34, 34, 34)
                .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ingresarEvaluacionLayout.createSequentialGroup()
                        .addComponent(txtTelPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ingresarEvaluacionLayout.createSequentialGroup()
                        .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMailPersona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(txtCiPersona, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ingresarEvaluacionLayout.createSequentialGroup()
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarEvaluacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviarEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        ingresarEvaluacionLayout.setVerticalGroup(
            ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarEvaluacionLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMailPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCiPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(ingresarEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnEnviarEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnAtrasEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(ingresarEvaluacion);

        opcionesEmpleado.setLayout(null);

        btnAtrasOpEmpleado.setText("volver");
        btnAtrasOpEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasOpEmpleadoActionPerformed(evt);
            }
        });
        opcionesEmpleado.add(btnAtrasOpEmpleado);
        btnAtrasOpEmpleado.setBounds(0, 570, 70, 30);

        btnEditarRestaurante.setText("Editar restaurante");
        btnEditarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRestauranteActionPerformed(evt);
            }
        });
        opcionesEmpleado.add(btnEditarRestaurante);
        btnEditarRestaurante.setBounds(220, 300, 140, 60);

        btnSortear.setText("Sortear");
        btnSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortearActionPerformed(evt);
            }
        });
        opcionesEmpleado.add(btnSortear);
        btnSortear.setBounds(410, 300, 120, 60);

        btnVerEvaluaciones.setText("Ver Evaluaciones");
        btnVerEvaluaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEvaluacionesActionPerformed(evt);
            }
        });
        opcionesEmpleado.add(btnVerEvaluaciones);
        btnVerEvaluaciones.setBounds(220, 380, 140, 60);

        btnVerSorteos.setText("Ver sorteos");
        btnVerSorteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSorteosActionPerformed(evt);
            }
        });
        opcionesEmpleado.add(btnVerSorteos);
        btnVerSorteos.setBounds(410, 380, 120, 60);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        opcionesEmpleado.add(jLabel17);
        jLabel17.setBounds(0, 0, 800, 600);

        getContentPane().add(opcionesEmpleado);

        editarRestaurante.setBackground(new java.awt.Color(219, 182, 173));

        btnAtrasRestaurante.setText("volver");
        btnAtrasRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasRestauranteActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Direccion");

        jLabel3.setText("Horario");

        jLabel4.setText("Tipo comida");

        btnGuardarRestaurante.setText("Guardar");
        btnGuardarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRestauranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarRestauranteLayout = new javax.swing.GroupLayout(editarRestaurante);
        editarRestaurante.setLayout(editarRestauranteLayout);
        editarRestauranteLayout.setHorizontalGroup(
            editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarRestauranteLayout.createSequentialGroup()
                .addComponent(btnAtrasRestaurante)
                .addGap(0, 737, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarRestauranteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarRestauranteLayout.createSequentialGroup()
                        .addGroup(editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(editarRestauranteLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34)
                                .addComponent(txtTipoComidaRest, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editarRestauranteLayout.createSequentialGroup()
                                .addGroup(editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHorarioRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccionRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarRestauranteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );
        editarRestauranteLayout.setVerticalGroup(
            editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarRestauranteLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccionRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHorarioRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editarRestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTipoComidaRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(btnGuardarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnAtrasRestaurante))
        );

        getContentPane().add(editarRestaurante);

        sortear.setBackground(new java.awt.Color(219, 182, 173));

        btnAtrasRealizarSorteo.setText("volver");
        btnAtrasRealizarSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasRealizarSorteoActionPerformed(evt);
            }
        });

        btnRealizarSorteo.setText("Sortear");
        btnRealizarSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarSorteoActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad de ganadores:");

        jLabel6.setText("Premio:");

        txtCantGanadoresSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantGanadoresSorteoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sortearLayout = new javax.swing.GroupLayout(sortear);
        sortear.setLayout(sortearLayout);
        sortearLayout.setHorizontalGroup(
            sortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortearLayout.createSequentialGroup()
                .addComponent(btnAtrasRealizarSorteo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(sortearLayout.createSequentialGroup()
                .addGroup(sortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sortearLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(btnRealizarSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sortearLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(sortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGanadores, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sortearLayout.createSequentialGroup()
                                .addGroup(sortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(sortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPremioSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantGanadoresSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        sortearLayout.setVerticalGroup(
            sortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sortearLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(sortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantGanadoresSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sortearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPremioSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btnRealizarSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblGanadores, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnAtrasRealizarSorteo))
        );

        getContentPane().add(sortear);

        evaluaciones.setBackground(new java.awt.Color(219, 182, 173));

        btnAtrasVerEvaluaciones.setText("volver");
        btnAtrasVerEvaluaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasVerEvaluacionesActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nombre", "estrellas", "correo", "telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelEvaluaciones.setViewportView(jTable1);

        btnVer1Evaluacion.setText("ver");
        btnVer1Evaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer1EvaluacionActionPerformed(evt);
            }
        });

        btnEliminarEvaluacion.setText("eliminar");
        btnEliminarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEvaluacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout evaluacionesLayout = new javax.swing.GroupLayout(evaluaciones);
        evaluaciones.setLayout(evaluacionesLayout);
        evaluacionesLayout.setHorizontalGroup(
            evaluacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evaluacionesLayout.createSequentialGroup()
                .addComponent(btnAtrasVerEvaluaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 730, Short.MAX_VALUE))
            .addGroup(evaluacionesLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(evaluacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(evaluacionesLayout.createSequentialGroup()
                        .addComponent(btnEliminarEvaluacion)
                        .addGap(18, 18, 18)
                        .addComponent(btnVer1Evaluacion))
                    .addComponent(panelEvaluaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        evaluacionesLayout.setVerticalGroup(
            evaluacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evaluacionesLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelEvaluaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(evaluacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVer1Evaluacion)
                    .addComponent(btnEliminarEvaluacion))
                .addGap(34, 34, 34)
                .addComponent(btnAtrasVerEvaluaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(evaluaciones);

        verEvaluacion.setBackground(new java.awt.Color(219, 182, 173));

        btnAtrasVerEvaluacion.setText("volver");
        btnAtrasVerEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasVerEvaluacionActionPerformed(evt);
            }
        });

        jLabel19.setText("Estrellas:");

        jLabel20.setText("Reseña:");

        jLabel21.setText("CI:");

        e1.setBackground(new java.awt.Color(219, 182, 173));
        e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        e1.setBorderPainted(false);
        e1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                e1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                e1FocusLost(evt);
            }
        });
        e1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e1MouseExited(evt);
            }
        });
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });

        e2.setBackground(new java.awt.Color(219, 182, 173));
        e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        e2.setBorderPainted(false);
        e2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                e2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                e2FocusLost(evt);
            }
        });
        e2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e2MouseExited(evt);
            }
        });
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });

        e3.setBackground(new java.awt.Color(219, 182, 173));
        e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        e3.setBorderPainted(false);
        e3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                e3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                e3FocusLost(evt);
            }
        });
        e3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e3MouseExited(evt);
            }
        });
        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });

        e4.setBackground(new java.awt.Color(219, 182, 173));
        e4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        e4.setBorderPainted(false);
        e4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                e4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                e4FocusLost(evt);
            }
        });
        e4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e4MouseExited(evt);
            }
        });
        e4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e4ActionPerformed(evt);
            }
        });

        e5.setBackground(new java.awt.Color(219, 182, 173));
        e5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png"))); // NOI18N
        e5.setBorderPainted(false);
        e5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                e5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                e5FocusLost(evt);
            }
        });
        e5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                e5MouseExited(evt);
            }
        });
        e5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e5ActionPerformed(evt);
            }
        });

        jLabel22.setText("Nombre:");

        jLabel23.setText("Telefono:");

        jLabel24.setText("Correo:");

        jLabel25.setText("jLabel25");

        jLabel26.setText("jLabel25");

        jLabel27.setText("jLabel25");

        jLabel28.setText("jLabel25");

        jLabel29.setText("jLabel25");

        javax.swing.GroupLayout verEvaluacionLayout = new javax.swing.GroupLayout(verEvaluacion);
        verEvaluacion.setLayout(verEvaluacionLayout);
        verEvaluacionLayout.setHorizontalGroup(
            verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verEvaluacionLayout.createSequentialGroup()
                .addComponent(btnAtrasVerEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 730, Short.MAX_VALUE))
            .addGroup(verEvaluacionLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(33, 33, 33)
                .addGroup(verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addGroup(verEvaluacionLayout.createSequentialGroup()
                        .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verEvaluacionLayout.setVerticalGroup(
            verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verEvaluacionLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel28))
                .addGap(21, 21, 21)
                .addGroup(verEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(btnAtrasVerEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(verEvaluacion);

        sorteos.setBackground(new java.awt.Color(219, 182, 173));

        btnVolverVerSorteos.setText("volver");
        btnVolverVerSorteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverVerSorteosActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "cantidad de ganadores", "premio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelSorteos.setViewportView(jTable2);

        btnVer1Sorteo.setText("ver");
        btnVer1Sorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer1SorteoActionPerformed(evt);
            }
        });

        btnEliminarSorteo.setText("eliminar");
        btnEliminarSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSorteoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sorteosLayout = new javax.swing.GroupLayout(sorteos);
        sorteos.setLayout(sorteosLayout);
        sorteosLayout.setHorizontalGroup(
            sorteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteosLayout.createSequentialGroup()
                .addComponent(btnVolverVerSorteos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 730, Short.MAX_VALUE))
            .addGroup(sorteosLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(sorteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sorteosLayout.createSequentialGroup()
                        .addComponent(btnEliminarSorteo)
                        .addGap(18, 18, 18)
                        .addComponent(btnVer1Sorteo))
                    .addComponent(panelSorteos, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sorteosLayout.setVerticalGroup(
            sorteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorteosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelSorteos, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(sorteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVer1Sorteo)
                    .addComponent(btnEliminarSorteo))
                .addGap(34, 34, 34)
                .addComponent(btnVolverVerSorteos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(sorteos);

        verSorteo.setBackground(new java.awt.Color(219, 182, 173));

        btnAtrasVerSorteo.setText("volver");
        btnAtrasVerSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasVerSorteoActionPerformed(evt);
            }
        });

        jLabel33.setText("Cantidad de ganadores:");

        jLabel34.setText("Premio:");

        jLabel35.setText("Ganadores:");

        jLabel36.setText("jLabel25");

        jLabel37.setText("jLabel25");

        jLabel38.setText("jLabel25");

        javax.swing.GroupLayout verSorteoLayout = new javax.swing.GroupLayout(verSorteo);
        verSorteo.setLayout(verSorteoLayout);
        verSorteoLayout.setHorizontalGroup(
            verSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verSorteoLayout.createSequentialGroup()
                .addComponent(btnAtrasVerSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 730, Short.MAX_VALUE))
            .addGroup(verSorteoLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(verSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addGap(34, 34, 34)
                .addGroup(verSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verSorteoLayout.setVerticalGroup(
            verSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verSorteoLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(verSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(verSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(verSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(btnAtrasVerSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(verSorteo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRestauranteActionPerformed
        restaurante.setNombre(txtNombreRest.getText());
        restaurante.setDireccion(txtDireccionRest.getText());
        restaurante.setHorario(txtHorarioRest.getText());
        restaurante.setTipoComida(txtTipoComidaRest.getText());
        JOptionPane.showMessageDialog(this, "Guardado correctamente.");
        this.esconder();
        opcionesEmpleado.setVisible(true);
    }//GEN-LAST:event_btnGuardarRestauranteActionPerformed

    private void txtCantGanadoresSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantGanadoresSorteoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantGanadoresSorteoActionPerformed

    private void btnEnviarEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEvaluacionActionPerformed
        boolean telCorrecto = Persona.validarTelefono(txtTelPersona.getText());
        boolean correoCorrecto = Persona.verificarCorreo(txtMailPersona.getText());
        boolean ciCorrecta = Persona.verificarCI(txtCiPersona.getText());
        if (telCorrecto && correoCorrecto && ciCorrecta) {
            Evaluacion evaluacion = new Evaluacion();
            evaluacion.getPersona().setNombre(txtNombrePersona.getText());
            if (txtTelPersona.getText().equals("")) {
                evaluacion.getPersona().setTelefono(0);
            } else {
                evaluacion.getPersona().setTelefono(Integer.parseInt(txtTelPersona.getText()));
            }
            evaluacion.getPersona().setMail(txtMailPersona.getText());
            evaluacion.getPersona().setCi(Integer.parseInt(txtCiPersona.getText()));
            if (cantidadEstrellas == 0) {
                cantidadEstrellas = 1;
            }
            evaluacion.setEstrellas(cantidadEstrellas);
            evaluacion.setResenia(txtReseniaPersona.getText());
            restaurante.getEvaluaciones().add(evaluacion);
            JOptionPane.showMessageDialog(this, "Ingresado correctamente.");
            this.esconder();
            inicio.setVisible(true);
            cantidadEstrellas = 0;

        } else {
            jLabel12.setVisible(!correoCorrecto);
            jLabel13.setVisible(!telCorrecto);
            jLabel14.setVisible(!ciCorrecta);
        }
    }//GEN-LAST:event_btnEnviarEvaluacionActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        this.esconder();
        ingresarEvaluacion.setVisible(true);
        this.iniEvaluacion();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        this.esconder();
        opcionesEmpleado.setVisible(true);
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnAtrasEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasEvaluacionActionPerformed
        this.esconder();
        inicio.setVisible(true);

    }//GEN-LAST:event_btnAtrasEvaluacionActionPerformed

    private void btnAtrasOpEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasOpEmpleadoActionPerformed
        this.esconder();
        inicio.setVisible(true);
    }//GEN-LAST:event_btnAtrasOpEmpleadoActionPerformed

    private void btnEnviarEvaluacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEnviarEvaluacionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarEvaluacionFocusGained

    private void btnEnviarEvaluacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEnviarEvaluacionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarEvaluacionFocusLost

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        cantidadEstrellas = 1;
        clickBoton(1);
    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        cantidadEstrellas = 2;
        clickBoton(2);
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        clickBoton(3);
        cantidadEstrellas = 3;
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        clickBoton(4);
        cantidadEstrellas = 4;// TODO add your handling code here:
    }//GEN-LAST:event_s4ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        clickBoton(5);
        cantidadEstrellas = 5;
    }//GEN-LAST:event_s5ActionPerformed

    private void s1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s1FocusGained
        clickBoton(1);
    }//GEN-LAST:event_s1FocusGained

    private void s1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s1FocusLost
        clickBoton(cantidadEstrellas);
    }//GEN-LAST:event_s1FocusLost

    private void s2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s2FocusGained
        clickBoton(2);    // TODO add your handling code here:
    }//GEN-LAST:event_s2FocusGained

    private void s2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s2FocusLost
        clickBoton(cantidadEstrellas);
    }//GEN-LAST:event_s2FocusLost

    private void s3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s3FocusLost
        clickBoton(cantidadEstrellas);
    }//GEN-LAST:event_s3FocusLost

    private void s4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s4FocusLost
        clickBoton(cantidadEstrellas);
    }//GEN-LAST:event_s4FocusLost

    private void s5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s5FocusLost
        clickBoton(cantidadEstrellas);
    }//GEN-LAST:event_s5FocusLost

    private void s3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s3FocusGained
        clickBoton(3);
    }//GEN-LAST:event_s3FocusGained

    private void s4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s4FocusGained
        clickBoton(4);
    }//GEN-LAST:event_s4FocusGained

    private void s5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s5FocusGained
        clickBoton(5);
    }//GEN-LAST:event_s5FocusGained

    private void s1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseEntered
        clickBoton(1);
    }//GEN-LAST:event_s1MouseEntered

    private void s2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseEntered
        clickBoton(2);
    }//GEN-LAST:event_s2MouseEntered

    private void s3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseEntered
        clickBoton(3);
    }//GEN-LAST:event_s3MouseEntered

    private void s4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s4MouseEntered
        clickBoton(4);
    }//GEN-LAST:event_s4MouseEntered

    private void s5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s5MouseEntered
        clickBoton(5);
    }//GEN-LAST:event_s5MouseEntered

    private void s1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseExited
        clickBoton(cantidadEstrellas);
    }//GEN-LAST:event_s1MouseExited

    private void s2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseExited
        clickBoton(cantidadEstrellas);        // TODO add your handling code here:
    }//GEN-LAST:event_s2MouseExited

    private void s3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseExited
        clickBoton(cantidadEstrellas);        // TODO add your handling code here:
    }//GEN-LAST:event_s3MouseExited

    private void s4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s4MouseExited
        clickBoton(cantidadEstrellas);        // TODO add your handling code here:
    }//GEN-LAST:event_s4MouseExited

    private void s5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s5MouseExited
        clickBoton(cantidadEstrellas);        // TODO add your handling code here:
    }//GEN-LAST:event_s5MouseExited

    private void btnSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortearActionPerformed
        this.esconder();
        sortear.setVisible(true);
        txtCantGanadoresSorteo.setText("");
        txtPremioSorteo.setText("");
        lblGanadores.setText("");
    }//GEN-LAST:event_btnSortearActionPerformed

    private void btnEditarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRestauranteActionPerformed
        this.esconder();
        this.inicializarRestaurante();
        editarRestaurante.setVisible(true);
    }//GEN-LAST:event_btnEditarRestauranteActionPerformed

    private void btnAtrasRealizarSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasRealizarSorteoActionPerformed
        this.esconder();
        opcionesEmpleado.setVisible(true);
    }//GEN-LAST:event_btnAtrasRealizarSorteoActionPerformed

    private void btnVerEvaluacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEvaluacionesActionPerformed
        if (!restaurante.getEvaluaciones().isEmpty()) {
            this.inicializarEvaluaciones();
            this.esconder();
            evaluaciones.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se han encontrado evaluaciones");
        }
    }//GEN-LAST:event_btnVerEvaluacionesActionPerformed

    private void btnVerSorteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSorteosActionPerformed
        if (!restaurante.getSorteos().isEmpty()) {
            this.inicializarSorteos();
            this.esconder();
            sorteos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se han encontrado sorteos");
        }
    }//GEN-LAST:event_btnVerSorteosActionPerformed

    private void btnAtrasVerEvaluacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasVerEvaluacionesActionPerformed
        this.esconder();
        opcionesEmpleado.setVisible(true);
    }//GEN-LAST:event_btnAtrasVerEvaluacionesActionPerformed

    private void btnAtrasRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasRestauranteActionPerformed
        this.esconder();
        opcionesEmpleado.setVisible(true);
    }//GEN-LAST:event_btnAtrasRestauranteActionPerformed

    private void btnAtrasVerEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasVerEvaluacionActionPerformed
        this.esconder();
        evaluaciones.setVisible(true);
    }//GEN-LAST:event_btnAtrasVerEvaluacionActionPerformed

    private void btnEliminarEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEvaluacionActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            int i = JOptionPane.showConfirmDialog(null, "Desea eliminar esta reseña?", null, YES_NO_OPTION);
            if (i == 0) {
                restaurante.getEvaluaciones().remove(jTable1.getSelectedRow());
                this.inicializarEvaluaciones();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una evaluacion.");
        }
    }//GEN-LAST:event_btnEliminarEvaluacionActionPerformed

    private void e1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_e1FocusGained

    private void e1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_e1FocusLost

    private void e1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e1MouseEntered

    private void e1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e1MouseExited

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    private void e2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_e2FocusGained

    private void e2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_e2FocusLost

    private void e2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e2MouseEntered

    private void e2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e2MouseExited

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e2ActionPerformed

    private void e3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_e3FocusGained

    private void e3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_e3FocusLost

    private void e3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e3MouseEntered

    private void e3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e3MouseExited

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e3ActionPerformed

    private void e4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_e4FocusGained

    private void e4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_e4FocusLost

    private void e4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e4MouseEntered

    private void e4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e4MouseExited

    private void e4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e4ActionPerformed

    private void e5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_e5FocusGained

    private void e5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_e5FocusLost

    private void e5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_e5MouseEntered

    private void e5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_e5MouseExited

    private void e5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e5ActionPerformed

    private void btnVer1EvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer1EvaluacionActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            this.esconder();
            verEvaluacion.setVisible(true);
            jLabel25.setText(restaurante.getEvaluaciones().get(jTable1.getSelectedRow()).getPersona().getNombre());
            jLabel26.setText("" + restaurante.getEvaluaciones().get(jTable1.getSelectedRow()).getPersona().getTelefono());
            jLabel27.setText("" + restaurante.getEvaluaciones().get(jTable1.getSelectedRow()).getPersona().getMail());
            jLabel28.setText("" + restaurante.getEvaluaciones().get(jTable1.getSelectedRow()).getPersona().getCi());
            jLabel29.setText("" + restaurante.getEvaluaciones().get(jTable1.getSelectedRow()).getResenia());
            this.cargarEstrellasResenia(restaurante.getEvaluaciones().get(jTable1.getSelectedRow()).getEstrellas());
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una evaluacion.");
        }
    }//GEN-LAST:event_btnVer1EvaluacionActionPerformed

    private void btnVolverVerSorteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverVerSorteosActionPerformed
        this.esconder();
        opcionesEmpleado.setVisible(true);
    }//GEN-LAST:event_btnVolverVerSorteosActionPerformed

    private void btnVer1SorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer1SorteoActionPerformed
        if (jTable2.getSelectedRow() != -1) {
            this.esconder();
            verSorteo.setVisible(true);
            jLabel36.setText("" + restaurante.getSorteos().get(jTable2.getSelectedRow()).getCantidadGanadores());
            jLabel37.setText(restaurante.getSorteos().get(jTable2.getSelectedRow()).getPremio());
            String text = "<html><body>";
            for (int i = 0; i < restaurante.getSorteos().get(jTable2.getSelectedRow()).getGanadores().size(); i++) {
                text += restaurante.getSorteos().get(jTable2.getSelectedRow()).getGanadores().get(i).getNombre() + "<br>";
            }
            text += "</body></html>";
            jLabel38.setText(text);

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un sorteo.");
        }
    }//GEN-LAST:event_btnVer1SorteoActionPerformed

    private void btnEliminarSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSorteoActionPerformed
        if (jTable2.getSelectedRow() != -1) {
            int i = JOptionPane.showConfirmDialog(null, "Desea eliminar este sorteo?", null, YES_NO_OPTION);
            if (i == 0) {
                restaurante.getSorteos().remove(jTable2.getSelectedRow());
                this.inicializarSorteos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un sorteo.");
        }
    }//GEN-LAST:event_btnEliminarSorteoActionPerformed

    private void btnAtrasVerSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasVerSorteoActionPerformed
        this.esconder();
        this.inicializarSorteos();
        sorteos.setVisible(true);
    }//GEN-LAST:event_btnAtrasVerSorteoActionPerformed

    private void btnRealizarSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarSorteoActionPerformed

        if ((!txtCantGanadoresSorteo.getText().isEmpty()) && (!restaurante.getEvaluaciones().isEmpty())) {

            boolean ingresaNum = false;
            int totalGanadores = 0;
            try {
                totalGanadores = Integer.parseInt(txtCantGanadoresSorteo.getText());
                ingresaNum = true;
            } catch (NumberFormatException e) {
                ingresaNum = false;
            }
            if (ingresaNum && totalGanadores > 0) {
                Sorteo s = new Sorteo();
                ArrayList<Persona> ganadores = new ArrayList<Persona>();
                Random r = new Random();
                //Copio evaluaciones
                ArrayList<Evaluacion> evaluacionesC = new ArrayList<Evaluacion>();
                for (int i = 0; i < restaurante.getEvaluaciones().size(); i++) {
                    evaluacionesC.add(restaurante.getEvaluaciones().get(i));
                }

                //Sorteo
                boolean correcto = true;
                for (int i = 0; (i < totalGanadores) && correcto; i++) {
                    if (evaluacionesC.size() > 0) {
                        int numRand = r.nextInt(evaluacionesC.size());
                        Persona posibleGanador = evaluacionesC.get(numRand).getPersona();
                        boolean yaGano = false;
                        for (int j = 0; j < i; j++) {
                            if (posibleGanador.getCi() == ganadores.get(j).getCi()) {
                                yaGano = true;
                                evaluacionesC.remove(evaluacionesC.get(numRand));
                            }
                        }
                        if (!yaGano) {
                            ganadores.add(posibleGanador);
                            evaluacionesC.remove(evaluacionesC.get(numRand));
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Hay más ganadores que clientes");
                        correcto = false;
                    }
                }

                //Anuncio ganadores
                s.setCantidadGanadores(totalGanadores);
                s.setPremio(txtPremioSorteo.getText());

                String text = "<html><body>Los ganadores son: <br>";
                for (int i = 0; i < ganadores.size(); i++) {
                    text += ganadores.get(i).getNombre() + "<br>";
                    s.addGanador(ganadores.get(i));
                }
                text += "</body></html>";
                lblGanadores.setText(text);
                s.notificarGanadores();
                JOptionPane.showMessageDialog(this, "Se le ha enviado un email a los ganadores del sorteo");
                restaurante.getSorteos().add(s);
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un numero correcto para cantidad de ganadores");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan datos para realizar el sorteo");
        }
    }//GEN-LAST:event_btnRealizarSorteoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasEvaluacion;
    private javax.swing.JButton btnAtrasOpEmpleado;
    private javax.swing.JButton btnAtrasRealizarSorteo;
    private javax.swing.JButton btnAtrasRestaurante;
    private javax.swing.JButton btnAtrasVerEvaluacion;
    private javax.swing.JButton btnAtrasVerEvaluaciones;
    private javax.swing.JButton btnAtrasVerSorteo;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEditarRestaurante;
    private javax.swing.JButton btnEliminarEvaluacion;
    private javax.swing.JButton btnEliminarSorteo;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnEnviarEvaluacion;
    private javax.swing.JButton btnGuardarRestaurante;
    private javax.swing.JButton btnRealizarSorteo;
    private javax.swing.JButton btnSortear;
    private javax.swing.JButton btnVer1Evaluacion;
    private javax.swing.JButton btnVer1Sorteo;
    private javax.swing.JButton btnVerEvaluaciones;
    private javax.swing.JButton btnVerSorteos;
    private javax.swing.JButton btnVolverVerSorteos;
    private javax.swing.JButton e1;
    private javax.swing.JButton e2;
    private javax.swing.JButton e3;
    private javax.swing.JButton e4;
    private javax.swing.JButton e5;
    private javax.swing.JPanel editarRestaurante;
    private javax.swing.JPanel evaluaciones;
    private javax.swing.JPanel ingresarEvaluacion;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblGanadores;
    private javax.swing.JPanel opcionesEmpleado;
    private javax.swing.JScrollPane panelEvaluaciones;
    private javax.swing.JScrollPane panelSorteos;
    private javax.swing.JButton s1;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton s4;
    private javax.swing.JButton s5;
    private javax.swing.JPanel sortear;
    private javax.swing.JPanel sorteos;
    private javax.swing.JTextField txtCantGanadoresSorteo;
    private javax.swing.JTextField txtCiPersona;
    private javax.swing.JTextField txtDireccionRest;
    private javax.swing.JTextField txtHorarioRest;
    private javax.swing.JTextField txtMailPersona;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtNombreRest;
    private javax.swing.JTextField txtPremioSorteo;
    private javax.swing.JTextArea txtReseniaPersona;
    private javax.swing.JTextField txtTelPersona;
    private javax.swing.JTextField txtTipoComidaRest;
    private javax.swing.JPanel verEvaluacion;
    private javax.swing.JPanel verSorteo;
    // End of variables declaration//GEN-END:variables

    private void esconder() {
        editarRestaurante.setVisible(false);
        ingresarEvaluacion.setVisible(false);
        verEvaluacion.setVisible(false);
        evaluaciones.setVisible(false);
        verSorteo.setVisible(false);
        sorteos.setVisible(false);
        opcionesEmpleado.setVisible(false);
        sortear.setVisible(false);
        inicio.setVisible(false);
    }

    private void iniEvaluacion() {
        txtNombrePersona.setText("");
        txtTelPersona.setText("");
        jLabel13.setVisible(false);
        txtMailPersona.setText("");
        jLabel12.setVisible(false);
        txtReseniaPersona.setText("");
        txtCiPersona.setText("");
        jLabel14.setVisible(false);
    }

    private void clickBoton(int nroBoton) {

        switch (nroBoton) {
            case 0:
                s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 1:
                s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 2:
                s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 3:
                s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 4:
                s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 5:
                s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                break;
        }
    }

    private void inicializarRestaurante() {
        txtNombreRest.setText(restaurante.getNombre());
        txtDireccionRest.setText(restaurante.getDireccion());
        txtHorarioRest.setText(restaurante.getHorario());
        txtTipoComidaRest.setText(restaurante.getTipoComida());
    }

    private void inicializarEvaluaciones() {
        ArrayList<Evaluacion> lista = restaurante.getEvaluaciones();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        while (model.getRowCount() != 0) {
            model.removeRow(0);
        }
        for (int i = 0; i < lista.size(); i++) {
            String[] aux = new String[4];
            aux[0] = lista.get(i).getPersona().getNombre();
            aux[1] = "" + lista.get(i).getEstrellas();
            aux[2] = lista.get(i).getPersona().getMail();
            aux[3] = "" + lista.get(i).getPersona().getTelefono();
            model.addRow((Object[]) aux);
        }
        jTable1.setVisible(true);
        jTable1.setModel(model);
    }

    private void cargarEstrellasResenia(int cantidad) {

        switch (cantidad) {
            case 0:
                e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 1:
                e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 2:
                e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 3:
                e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                e5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 4:
                e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e0.png")));
                break;
            case 5:
                e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                e5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/e1.png")));
                break;
        }
    }

    private void inicializarSorteos() {
        ArrayList<Sorteo> lista = restaurante.getSorteos();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        while (model.getRowCount() != 0) {
            model.removeRow(0);
        }
        for (int i = 0; i < lista.size(); i++) {
            String[] aux = new String[2];
            aux[0] = "" + lista.get(i).getCantidadGanadores();
            aux[1] = "" + lista.get(i).getPremio();
            model.addRow((Object[]) aux);
        }
        jTable2.setVisible(true);
        jTable2.setModel(model);
    }

}
